# Generated by Django 3.0.9 on 2020-09-11 16:17
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations
from django.db.models.signals import pre_save
from edc_constants.constants import NO, UNKNOWN
from edc_utils import DisableSignals


def update_complications_from_baseline(apps, schema_editor):
    complications_baseline_model_cls = apps.get_model(
        "inte_subject.complicationsbaseline"
    )
    complications_model_cls = apps.get_model("inte_subject.complications")
    clinical_review_model_cls = apps.get_model("inte_subject.clinicalreview")
    names = [
        "stroke",
        "heart_attack",
        "renal_disease",
        "vision",
        "numbness",
        "foot_ulcers",
    ]
    for name in names:
        clinical_review_model_cls.objects.filter(**{name: UNKNOWN}).update(**{name: NO})

    for clinical_review in clinical_review_model_cls.objects.all():
        try:
            complications_baseline = complications_baseline_model_cls.objects.get(
                subject_visit=clinical_review.subject_visit
            )
        except ObjectDoesNotExist:
            pass
        else:
            complications = complications_model_cls()

            complications.subject_visit = clinical_review.subject_visit

            for name in names:
                setattr(complications, name, complications_baseline.stroke)
                setattr(
                    complications,
                    f"{name}_date",
                    getattr(complications_baseline, f"{name}_estimated_date"),
                )

            complications.complications = complications_baseline.complications

            complications.other_complications = (
                complications_baseline.other_complications
            )
            with DisableSignals(disabled_signals=[pre_save]):
                complications.save()


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0058_auto_20200911_1848"),
    ]

    operations = [migrations.RunPython(update_complications_from_baseline)]
