# Generated by Django 2.2.9 on 2020-02-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_consent", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsubjectconsent", name="completed_by_next_of_kin",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectconsent", name="hospital_identifier",
        ),
        migrations.RemoveField(
            model_name="subjectconsent", name="completed_by_next_of_kin",
        ),
        migrations.RemoveField(
            model_name="subjectconsent", name="hospital_identifier",
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsent",
            name="identity_type",
            field=models.CharField(
                choices=[
                    ("country_id", "Country ID number"),
                    ("drivers", "Driver's license"),
                    ("passport", "Passport"),
                    ("hospital_no", "Hospital number"),
                    ("country_id_rcpt", "Country ID receipt"),
                    ("mobile_no", "Mobile number"),
                    ("OTHER", "Other"),
                ],
                max_length=25,
                verbose_name="What type of identity number is this?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectconsent",
            name="identity_type",
            field=models.CharField(
                choices=[
                    ("country_id", "Country ID number"),
                    ("drivers", "Driver's license"),
                    ("passport", "Passport"),
                    ("hospital_no", "Hospital number"),
                    ("country_id_rcpt", "Country ID receipt"),
                    ("mobile_no", "Mobile number"),
                    ("OTHER", "Other"),
                ],
                max_length=25,
                verbose_name="What type of identity number is this?",
            ),
        ),
    ]
