# Generated by Django 2.2.9 on 2020-02-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_consent", "0002_auto_20200202_2301"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubjectconsent",
            name="clinic_type",
            field=models.CharField(
                choices=[("hiv_clinic", "HIV Clinic"), ("ncd_clinic", "NCD Clinic")],
                default="hiv_clinic",
                max_length=25,
                verbose_name="In which type of clinic was the patient screened",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subjectconsent",
            name="clinic_type",
            field=models.CharField(
                choices=[("hiv_clinic", "HIV Clinic"), ("ncd_clinic", "NCD Clinic")],
                default="hiv_clinic",
                max_length=25,
                verbose_name="In which type of clinic was the patient screened",
            ),
            preserve_default=False,
        ),
    ]
