# Generated by Django 3.0.6 on 2020-07-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_consent", "0003_auto_20200630_2200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectconsent",
            name="language",
            field=models.CharField(
                choices=[
                    ["lg", "Luganda"],
                    ["ry", "Runyakitara"],
                    ["en", "English"],
                    ["sw", "Swahili"],
                ],
                help_text="The language used for the consent process will also be used during data collection.",
                max_length=25,
                verbose_name="Language of consent",
            ),
        ),
        migrations.AlterField(
            model_name="subjectconsent",
            name="language",
            field=models.CharField(
                choices=[
                    ["lg", "Luganda"],
                    ["ry", "Runyakitara"],
                    ["en", "English"],
                    ["sw", "Swahili"],
                ],
                help_text="The language used for the consent process will also be used during data collection.",
                max_length=25,
                verbose_name="Language of consent",
            ),
        ),
    ]
