# Generated by Django 2.2.10 on 2020-02-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_consent", "0004_auto_20200220_2339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectconsent",
            name="clinic_type",
            field=models.CharField(
                choices=[("hiv_clinic", "HIV Clinic"), ("ncd_clinic", "NCD Clinic")],
                help_text="Should match that reported on the Screening form.",
                max_length=25,
                verbose_name="In which type of clinic was the patient screened",
            ),
        ),
        migrations.AlterField(
            model_name="subjectconsent",
            name="clinic_type",
            field=models.CharField(
                choices=[("hiv_clinic", "HIV Clinic"), ("ncd_clinic", "NCD Clinic")],
                help_text="Should match that reported on the Screening form.",
                max_length=25,
                verbose_name="In which type of clinic was the patient screened",
            ),
        ),
    ]
