from django.core.management import color_style
from edc_sites.single_site import SingleSite

style = color_style()

fqdn = "inte.clinicedc.org"


# site_id, name, **kwargs
all_sites = {
    "uganda": (
        SingleSite(
            101,
            "bugamba",
            country_code="ug",
            country="uganda",
            domain=f"bugamba.ug.{fqdn}",
        ),
        SingleSite(
            102,
            "bwizibwera",
            country_code="ug",
            country="uganda",
            domain=f"bwizibwera.ug.{fqdn}",
        ),
        SingleSite(
            103,
            "kinoni",
            country_code="ug",
            country="uganda",
            domain=f"kinoni.ug.{fqdn}",
        ),
        SingleSite(
            104,
            "ruhoko",
            country_code="ug",
            country="uganda",
            domain=f"ruhoko.ug.{fqdn}",
        ),
        SingleSite(
            105,
            "kyazanga",
            country_code="ug",
            country="uganda",
            domain=f"kyazanga.ug.{fqdn}",
        ),
        SingleSite(
            106,
            "bukulula",
            country_code="ug",
            country="uganda",
            domain=f"bukulula.ug.{fqdn}",
        ),
        SingleSite(
            107,
            "kojja",
            country_code="ug",
            country="uganda",
            domain=f"kojja.ug.{fqdn}",
        ),
        SingleSite(
            108,
            "mpigi",
            country_code="ug",
            country="uganda",
            domain=f"mpigi.ug.{fqdn}",
        ),
        SingleSite(
            109,
            "namayumba",
            country_code="ug",
            country="uganda",
            domain=f"namayumba.ug.{fqdn}",
        ),
        SingleSite(
            110,
            "buwambo",
            country_code="ug",
            country="uganda",
            domain=f"buwambo.ug.{fqdn}",
        ),
        SingleSite(
            111,
            "kajjansi",
            country_code="ug",
            country="uganda",
            domain=f"kajjansi.ug.{fqdn}",
        ),
        SingleSite(
            112,
            "tikalu",
            country_code="ug",
            country="uganda",
            domain=f"tikalu.ug.{fqdn}",
        ),
        SingleSite(
            113,
            "namulonge",
            country_code="ug",
            country="uganda",
            domain=f"namulonge.ug.{fqdn}",
        ),
        SingleSite(
            114,
            "kasanje",
            country_code="ug",
            country="uganda",
            domain=f"kasanje.ug.{fqdn}",
        ),
        SingleSite(
            115,
            "kasangati",
            country_code="ug",
            country="uganda",
            domain=f"kasangati.ug.{fqdn}",
        ),
        SingleSite(
            116,
            "sekiwunga",
            country_code="ug",
            country="uganda",
            domain=f"sekiwunga.ug.{fqdn}",
        ),
        SingleSite(
            117,
            "muduma",
            country_code="ug",
            country="uganda",
            domain=f"muduma.ug.{fqdn}",
        ),
        SingleSite(
            118,
            "kyamulibwa",
            country_code="ug",
            country="uganda",
            domain=f"kyamulibwa.ug.{fqdn}",
        ),
    )
}
