# Generated by Django 2.2.9 on 2020-02-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_screening", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsubjectscreening", name="diabetic",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectscreening", name="hiv_status",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectscreening", name="hypertensive",
        ),
        migrations.RemoveField(model_name="subjectscreening", name="diabetic",),
        migrations.RemoveField(model_name="subjectscreening", name="hiv_status",),
        migrations.RemoveField(model_name="subjectscreening", name="hypertensive",),
        migrations.AddField(
            model_name="historicalsubjectscreening",
            name="qualifying_condition",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Does the patient have at least one of the following conditions: HIV, Diabetes and/or Hypertension",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subjectscreening",
            name="qualifying_condition",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Does the patient have at least one of the following conditions: HIV, Diabetes and/or Hypertension",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="clinic_type",
            field=models.CharField(
                choices=[("ncd_clinic", "NCD Clinic"), ("hiv_clinic", "HIV Clinic")],
                max_length=25,
                verbose_name="From which clinic was the patient selected",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="clinic_type",
            field=models.CharField(
                choices=[("ncd_clinic", "NCD Clinic"), ("hiv_clinic", "HIV Clinic")],
                max_length=25,
                verbose_name="From which clinic was the patient selected",
            ),
        ),
    ]
