# Generated by Django 3.0.6 on 2020-07-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inte_screening", "0003_auto_20200630_2200"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsubjectrefusal",
            name="subject_identifier",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectrefusal",
            name="subject_identifier_aka",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectrefusal",
            name="subject_identifier_as_pk",
        ),
        migrations.RemoveField(
            model_name="historicalsubjectrefusal",
            name="subject_screening",
        ),
        migrations.RemoveField(
            model_name="subjectrefusal",
            name="subject_identifier",
        ),
        migrations.RemoveField(
            model_name="subjectrefusal",
            name="subject_identifier_aka",
        ),
        migrations.RemoveField(
            model_name="subjectrefusal",
            name="subject_identifier_as_pk",
        ),
        migrations.RemoveField(
            model_name="subjectrefusal",
            name="subject_screening",
        ),
    ]
