# Generated by Django 3.0.6 on 2020-07-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_screening", "0004_auto_20200702_2152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectrefusal",
            name="screening_identifier",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="subjectrefusal",
            name="screening_identifier",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
