# Generated by Django 3.0.6 on 2020-07-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_screening", "0007_dailyclosinglog_historicaldailyclosinglog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyclosinglog",
            options={
                "verbose_name": "Daily Closing Log",
                "verbose_name_plural": "Daily Closing Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldailyclosinglog",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Daily Closing Log",
            },
        ),
        migrations.RemoveField(
            model_name="dailyclosinglog",
            name="log_identifier",
        ),
        migrations.RemoveField(
            model_name="historicaldailyclosinglog",
            name="log_identifier",
        ),
        migrations.AlterField(
            model_name="dailyclosinglog",
            name="clinic_services",
            field=models.CharField(
                choices=[
                    ("integrated", "Integrated care day (HIV, Diabetes, Hypertension)"),
                    ("ncd", "NCD day (Diabetes + Hypertension)"),
                    ("HIV", "HIV only day"),
                    ("diabetes", "Diabetes only day"),
                    ("hypertension", "Hypertension only day"),
                ],
                max_length=25,
                verbose_name="Which services are being offered at the clinic today?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyclosinglog",
            name="clinic_services",
            field=models.CharField(
                choices=[
                    ("integrated", "Integrated care day (HIV, Diabetes, Hypertension)"),
                    ("ncd", "NCD day (Diabetes + Hypertension)"),
                    ("HIV", "HIV only day"),
                    ("diabetes", "Diabetes only day"),
                    ("hypertension", "Hypertension only day"),
                ],
                max_length=25,
                verbose_name="Which services are being offered at the clinic today?",
            ),
        ),
    ]
