# Generated by Django 3.0.6 on 2020-07-03 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_screening", "0008_auto_20200703_0410"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyclosinglog",
            name="agreed_to_screen",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Of those approached, how many agreed to be screened",
            ),
        ),
        migrations.AlterField(
            model_name="dailyclosinglog",
            name="approached",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Of those who attended, how many were approached by the study team",
            ),
        ),
        migrations.AlterField(
            model_name="dailyclosinglog",
            name="attended",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Total number of patients who attended the clinic today",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyclosinglog",
            name="agreed_to_screen",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Of those approached, how many agreed to be screened",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyclosinglog",
            name="approached",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Of those who attended, how many were approached by the study team",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyclosinglog",
            name="attended",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Total number of patients who attended the clinic today",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyclosinglog",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="dailyclosinglog",
            constraint=models.UniqueConstraint(
                fields=("log_date", "site"), name="unique_date_for_site"
            ),
        ),
    ]
