# Generated by Django 3.0.6 on 2020-07-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_screening", "0010_auto_20200703_0641"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="selection_method",
            field=models.CharField(
                choices=[
                    ("random_sampling", "Random sampling"),
                    ("systematic", "Systematically selected"),
                    ("sequential", "Sequentially selected"),
                    ("purposively_selected", "Purposively selected"),
                ],
                max_length=25,
                verbose_name="How was the patient selected for screening?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="selection_method",
            field=models.CharField(
                choices=[
                    ("random_sampling", "Random sampling"),
                    ("systematic", "Systematically selected"),
                    ("sequential", "Sequentially selected"),
                    ("purposively_selected", "Purposively selected"),
                ],
                max_length=25,
                verbose_name="How was the patient selected for screening?",
            ),
        ),
    ]
