# Generated by Django 3.0.6 on 2020-07-30 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inte_screening", "0011_auto_20200709_0819"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectrefusal",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
                "verbose_name": "Subject Refusal",
                "verbose_name_plural": "Subject Refusals",
            },
        ),
    ]
