# Generated by Django 3.0.6 on 2020-08-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_screening", "0012_auto_20200730_0710"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyclosinglog",
            name="selection_method",
            field=models.CharField(
                choices=[
                    ("random_sampling", "Random sampling"),
                    ("systematic", "Systematically selected"),
                    ("sequential", "Sequentially selected"),
                    ("purposively_selected", "Purposively selected"),
                ],
                max_length=25,
                verbose_name="How were patients selected to be approached?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyclosinglog",
            name="selection_method",
            field=models.CharField(
                choices=[
                    ("random_sampling", "Random sampling"),
                    ("systematic", "Systematically selected"),
                    ("sequential", "Sequentially selected"),
                    ("purposively_selected", "Purposively selected"),
                ],
                max_length=25,
                verbose_name="How were patients selected to be approached?",
            ),
        ),
    ]
