# Generated by Django 3.1.6 on 2021-05-09 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_screening", "0014_auto_20201002_2042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyclosinglog",
            name="agreed_to_screen",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Of those approached, how many agreed to be screened",
            ),
        ),
        migrations.AlterField(
            model_name="dailyclosinglog",
            name="approached",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Of those who attended, how many were approached by the study team",
            ),
        ),
        migrations.AlterField(
            model_name="dailyclosinglog",
            name="selection_method",
            field=models.CharField(
                choices=[
                    ("random_sampling", "Random sampling"),
                    ("systematic", "Systematically selected"),
                    ("sequential", "Sequentially selected"),
                    ("purposively_selected", "Purposively selected"),
                ],
                max_length=25,
                null=True,
                verbose_name="How were patients selected to be approached?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyclosinglog",
            name="agreed_to_screen",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Of those approached, how many agreed to be screened",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyclosinglog",
            name="approached",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Of those who attended, how many were approached by the study team",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyclosinglog",
            name="selection_method",
            field=models.CharField(
                choices=[
                    ("random_sampling", "Random sampling"),
                    ("systematic", "Systematically selected"),
                    ("sequential", "Sequentially selected"),
                    ("purposively_selected", "Purposively selected"),
                ],
                max_length=25,
                null=True,
                verbose_name="How were patients selected to be approached?",
            ),
        ),
    ]
