# Generated by Django 3.2.3 on 2021-05-18 23:19

import django.core.validators
from django.db import migrations, models
import edc_sites.models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_screening", "0014_auto_20201002_2042"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyClosingLogRevised",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inte_screening.dailyclosinglog",),
            managers=[
                ("on_site", edc_sites.models.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name="dailyclosinglog",
            name="clinic_end_time",
            field=models.TimeField(
                help_text="Use 24HRS format. For example 17:00",
                null=True,
                verbose_name="Clinic End time",
            ),
        ),
        migrations.AddField(
            model_name="dailyclosinglog",
            name="clinic_start_time",
            field=models.TimeField(
                help_text="Use 24HRS format. For example 17:00",
                null=True,
                verbose_name="Clinic start time",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyclosinglog",
            name="clinic_end_time",
            field=models.TimeField(
                help_text="Use 24HRS format. For example 17:00",
                null=True,
                verbose_name="Clinic End time",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyclosinglog",
            name="clinic_start_time",
            field=models.TimeField(
                help_text="Use 24HRS format. For example 17:00",
                null=True,
                verbose_name="Clinic start time",
            ),
        ),
        migrations.AlterField(
            model_name="dailyclosinglog",
            name="agreed_to_screen",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Of those approached, how many agreed to be screened",
            ),
        ),
        migrations.AlterField(
            model_name="dailyclosinglog",
            name="approached",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Of those who attended, how many were approached by the study team",
            ),
        ),
        migrations.AlterField(
            model_name="dailyclosinglog",
            name="selection_method",
            field=models.CharField(
                choices=[
                    ("random_sampling", "Random sampling"),
                    ("systematic", "Systematically selected"),
                    ("sequential", "Sequentially selected"),
                    ("purposively_selected", "Purposively selected"),
                ],
                max_length=25,
                null=True,
                verbose_name="How were patients selected to be approached?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyclosinglog",
            name="agreed_to_screen",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Of those approached, how many agreed to be screened",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyclosinglog",
            name="approached",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Of those who attended, how many were approached by the study team",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyclosinglog",
            name="selection_method",
            field=models.CharField(
                choices=[
                    ("random_sampling", "Random sampling"),
                    ("systematic", "Systematically selected"),
                    ("sequential", "Sequentially selected"),
                    ("purposively_selected", "Purposively selected"),
                ],
                max_length=25,
                null=True,
                verbose_name="How were patients selected to be approached?",
            ),
        ),
    ]
