# Generated by Django 3.2.3 on 2021-05-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inte_screening", "0015_auto_20210519_0219"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyclosinglogrevised",
            options={
                "verbose_name": "Daily Closing Log (post-enrollment)",
                "verbose_name_plural": "Daily Closing Logs (post-enrollment)",
            },
        ),
    ]
