# Generated by Django 3.1.6 on 2021-05-12 11:46

from django.db import migrations
import edc_sites.models


class Migration(migrations.Migration):

    dependencies = [
        ('inte_screening', '0016_auto_20210509_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClosingLogRevised',
            fields=[
            ],
            options={
                'verbose_name': 'Daily Closing Logs (Revised)',
                'verbose_name_plural': 'Daily Closing Logs (Revised)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inte_screening.dailyclosinglog',),
            managers=[
                ('on_site', edc_sites.models.CurrentSiteManager()),
            ],
        ),
    ]
