# Generated by Django 3.2.3 on 2021-05-24 16:21

from django.db import migrations
import inte_screening.models.daily_closing_log


class Migration(migrations.Migration):

    dependencies = [
        ("inte_screening", "0017_historicaldailyclosinglogrevised"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="dailyclosinglog",
            managers=[
                ("on_site", inte_screening.models.daily_closing_log.CurrentSiteManager()),
                ("objects", inte_screening.models.daily_closing_log.DailyClosingLogManager()),
            ],
        ),
    ]
