# Generated by Django 3.0.9 on 2020-09-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0047_auto_20200909_1956"),
        ("inte_lists", "0006_auto_20200812_0317"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DiabetesTreatments",
            new_name="DmTreatments",
        ),
        migrations.RenameModel(
            old_name="HypertensionTreatments",
            new_name="HtnTreatments",
        ),
        migrations.RemoveIndex(
            model_name="dmtreatments",
            name="inte_lists__id_5eae8d_idx",
        ),
        migrations.RemoveIndex(
            model_name="htntreatments",
            name="inte_lists__id_34d395_idx",
        ),
        migrations.AddIndex(
            model_name="dmtreatments",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="inte_lists__id_500684_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="htntreatments",
            index=models.Index(
                fields=["id", "display_name", "display_index"],
                name="inte_lists__id_cf28cb_idx",
            ),
        ),
    ]
