# Generated by Django 2.2.9 on 2020-02-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0002_auto_20200202_1111"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generalassessmentinitial",
            old_name="hiv_clinic_nearby",
            new_name="use_hiv_clinic_nearby",
        ),
        migrations.RenameField(
            model_name="generalassessmentinitial",
            old_name="ncd_clinic_nearby",
            new_name="use_ncd_clinic_nearby",
        ),
        migrations.RenameField(
            model_name="historicalgeneralassessmentinitial",
            old_name="hiv_clinic_nearby",
            new_name="use_hiv_clinic_nearby",
        ),
        migrations.RenameField(
            model_name="historicalgeneralassessmentinitial",
            old_name="ncd_clinic_nearby",
            new_name="use_ncd_clinic_nearby",
        ),
        migrations.RemoveField(
            model_name="generalassessmentinitial", name="hiv_status",
        ),
        migrations.RemoveField(
            model_name="historicalgeneralassessmentinitial", name="hiv_status",
        ),
        migrations.AddField(
            model_name="generalassessmentinitial",
            name="hiv",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                default="Yes",
                max_length=15,
                verbose_name="Have you previously tested <u>positive</u> for HIV",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalgeneralassessmentinitial",
            name="hiv",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                default="Yes",
                max_length=15,
                verbose_name="Have you previously tested <u>positive</u> for HIV",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="generalassessmentinitial",
            name="diabetic",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                verbose_name="Have you previously been diagnosed with <u>diabetes</u> (high blood sugar)?",
            ),
        ),
        migrations.AlterField(
            model_name="generalassessmentinitial",
            name="hypertensive",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                verbose_name="Have you previously been diagnosed with <u>hypertension</u> (high blood pressure)?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgeneralassessmentinitial",
            name="diabetic",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                verbose_name="Have you previously been diagnosed with <u>diabetes</u> (high blood sugar)?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgeneralassessmentinitial",
            name="hypertensive",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                verbose_name="Have you previously been diagnosed with <u>hypertension</u> (high blood pressure)?",
            ),
        ),
    ]
