# Generated by Django 3.0.6 on 2020-06-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0002_auto_20200623_1720"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complications",
            name="foot_ulcers",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                null=True,
                verbose_name="Foot ulcers",
            ),
        ),
        migrations.AlterField(
            model_name="complications",
            name="heart_attack",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                null=True,
                verbose_name="Heart attack / heart failure",
            ),
        ),
        migrations.AlterField(
            model_name="complications",
            name="numbness",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                null=True,
                verbose_name="Numbness / burning sensation",
            ),
        ),
        migrations.AlterField(
            model_name="complications",
            name="renal_disease",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                null=True,
                verbose_name="Renal (kidney) disease",
            ),
        ),
        migrations.AlterField(
            model_name="complications",
            name="stroke",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                null=True,
                verbose_name="Stroke",
            ),
        ),
        migrations.AlterField(
            model_name="complications",
            name="vision",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                null=True,
                verbose_name="Vision problems (e.g. blurred vision)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplications",
            name="foot_ulcers",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                null=True,
                verbose_name="Foot ulcers",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplications",
            name="heart_attack",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                null=True,
                verbose_name="Heart attack / heart failure",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplications",
            name="numbness",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                null=True,
                verbose_name="Numbness / burning sensation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplications",
            name="renal_disease",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                null=True,
                verbose_name="Renal (kidney) disease",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplications",
            name="stroke",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                null=True,
                verbose_name="Stroke",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplications",
            name="vision",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                null=True,
                verbose_name="Vision problems (e.g. blurred vision)",
            ),
        ),
    ]
