# Generated by Django 2.2.9 on 2020-02-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0003_auto_20200204_0939"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anthropometry",
            name="bmi",
            field=models.DecimalField(
                decimal_places=1,
                help_text="kg/mm^2 (Note: this field is read only. The value is calculated)",
                max_digits=7,
                verbose_name="BMI",
            ),
        ),
        migrations.AlterField(
            model_name="historicalanthropometry",
            name="bmi",
            field=models.DecimalField(
                decimal_places=1,
                help_text="kg/mm^2 (Note: this field is read only. The value is calculated)",
                max_digits=7,
                verbose_name="BMI",
            ),
        ),
    ]
