# Generated by Django 3.0.6 on 2020-06-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0005_auto_20200624_0335"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalnextappointment",
            name="diabetes_clinic_appt_date",
            field=models.DateField(
                blank=True,
                help_text="if applicable.",
                null=True,
                verbose_name="Diabetes-only clinic: next scheduled routine appointment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalnextappointment",
            name="hiv_clinic_appt_date",
            field=models.DateField(
                blank=True,
                help_text="if applicable.",
                null=True,
                verbose_name="HIV clinic: next scheduled routine appointment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalnextappointment",
            name="hypertension_clinic_appt_date",
            field=models.DateField(
                blank=True,
                help_text="if applicable.",
                null=True,
                verbose_name="Hypertension-only clinic: next scheduled routine appointment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalnextappointment",
            name="ncd_clinic_appt_date",
            field=models.DateField(
                blank=True,
                help_text="if applicable.",
                null=True,
                verbose_name="NCD clinic: next scheduled routine appointment",
            ),
        ),
        migrations.AlterField(
            model_name="nextappointment",
            name="diabetes_clinic_appt_date",
            field=models.DateField(
                blank=True,
                help_text="if applicable.",
                null=True,
                verbose_name="Diabetes-only clinic: next scheduled routine appointment",
            ),
        ),
        migrations.AlterField(
            model_name="nextappointment",
            name="hiv_clinic_appt_date",
            field=models.DateField(
                blank=True,
                help_text="if applicable.",
                null=True,
                verbose_name="HIV clinic: next scheduled routine appointment",
            ),
        ),
        migrations.AlterField(
            model_name="nextappointment",
            name="hypertension_clinic_appt_date",
            field=models.DateField(
                blank=True,
                help_text="if applicable.",
                null=True,
                verbose_name="Hypertension-only clinic: next scheduled routine appointment",
            ),
        ),
        migrations.AlterField(
            model_name="nextappointment",
            name="ncd_clinic_appt_date",
            field=models.DateField(
                blank=True,
                help_text="if applicable.",
                null=True,
                verbose_name="NCD clinic: next scheduled routine appointment",
            ),
        ),
    ]
