# Generated by Django 2.2.10 on 2020-02-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0008_auto_20200221_1738"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselinecarestatus",
            name="hiv_clinic_other_is_study_clinic",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Is this HIV clinic an INTE study clinic?",
            ),
        ),
        migrations.AddField(
            model_name="historicalbaselinecarestatus",
            name="hiv_clinic_other_is_study_clinic",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Is this HIV clinic an INTE study clinic?",
            ),
        ),
        migrations.AlterField(
            model_name="baselinecarestatus",
            name="diabetic",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                verbose_name="Have you previously been diagnosed with <u>diabetes</u>?",
            ),
        ),
        migrations.AlterField(
            model_name="baselinecarestatus",
            name="hiv_clinic_other",
            field=models.CharField(
                max_length=50,
                null=True,
                verbose_name="If <u>not</u> attending the HIV clinic in this facility, where do you attend?",
            ),
        ),
        migrations.AlterField(
            model_name="baselinecarestatus",
            name="hiv_willing_to_transfer",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=50,
                verbose_name="Would you be willing to transfer to the HIV clinic in this facility?",
            ),
        ),
        migrations.AlterField(
            model_name="baselinecarestatus",
            name="hypertensive",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                verbose_name="Have you previously been diagnosed with <u>hypertension</u>?",
            ),
        ),
        migrations.AlterField(
            model_name="baselinecarestatus",
            name="ncd_clinic_other",
            field=models.CharField(
                max_length=50,
                null=True,
                verbose_name="If not attending the NCD clinic in this facility, where do you attend?",
            ),
        ),
        migrations.AlterField(
            model_name="baselinecarestatus",
            name="ncd_willing_to_transfer",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=50,
                verbose_name="Would you be willing to transfer to the NCD clinic in this facility?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbaselinecarestatus",
            name="diabetic",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                verbose_name="Have you previously been diagnosed with <u>diabetes</u>?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbaselinecarestatus",
            name="hiv_clinic_other",
            field=models.CharField(
                max_length=50,
                null=True,
                verbose_name="If <u>not</u> attending the HIV clinic in this facility, where do you attend?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbaselinecarestatus",
            name="hiv_willing_to_transfer",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=50,
                verbose_name="Would you be willing to transfer to the HIV clinic in this facility?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbaselinecarestatus",
            name="hypertensive",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("unknown", "Unknown")],
                max_length=25,
                verbose_name="Have you previously been diagnosed with <u>hypertension</u>?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbaselinecarestatus",
            name="ncd_clinic_other",
            field=models.CharField(
                max_length=50,
                null=True,
                verbose_name="If not attending the NCD clinic in this facility, where do you attend?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbaselinecarestatus",
            name="ncd_willing_to_transfer",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=50,
                verbose_name="Would you be willing to transfer to the NCD clinic in this facility?",
            ),
        ),
    ]
