# Generated by Django 2.2.10 on 2020-02-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0009_auto_20200223_1626"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baselinecarestatus",
            name="hiv_clinic_other",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="If <u>not</u> attending the HIV clinic in this facility, where do you attend?",
            ),
        ),
        migrations.AlterField(
            model_name="baselinecarestatus",
            name="ncd_clinic_other",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="If not attending the NCD clinic in this facility, where do you attend?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbaselinecarestatus",
            name="hiv_clinic_other",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="If <u>not</u> attending the HIV clinic in this facility, where do you attend?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbaselinecarestatus",
            name="ncd_clinic_other",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="If not attending the NCD clinic in this facility, where do you attend?",
            ),
        ),
    ]
