# Generated by Django 3.0.6 on 2020-06-25 23:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inte_subject", "0009_auto_20200625_0638"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CareStatus",
            new_name="CareStatusBaseline",
        ),
        migrations.RenameModel(
            old_name="HistoricalCareStatus",
            new_name="HistoricalCareStatusBaseline",
        ),
        migrations.AlterModelOptions(
            name="carestatusbaseline",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
                "verbose_name": "Care Status: Baseline",
                "verbose_name_plural": "Care Status: Baseline",
            },
        ),
        migrations.AlterModelOptions(
            name="drugsupplyhiv",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
                "verbose_name": "Drug Supply: HIV",
                "verbose_name_plural": "Drug Supply: HIV",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcarestatusbaseline",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Care Status: Baseline",
            },
        ),
        migrations.RemoveIndex(
            model_name="carestatusbaseline",
            name="inte_subjec_subject_2f6eea_idx",
        ),
        migrations.RemoveField(
            model_name="historicalhivinitialreview",
            name="current_arv_regimen",
        ),
        migrations.RemoveField(
            model_name="historicalhivinitialreview",
            name="other_current_arv_regimen",
        ),
        migrations.RemoveField(
            model_name="hivinitialreview",
            name="current_arv_regimen",
        ),
        migrations.RemoveField(
            model_name="hivinitialreview",
            name="other_current_arv_regimen",
        ),
        migrations.AddIndex(
            model_name="carestatusbaseline",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="inte_subjec_subject_bf51eb_idx",
            ),
        ),
    ]
