# Generated by Django 2.2.10 on 2020-02-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0011_auto_20200224_2024"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baselinecarestatus",
            old_name="hiv_next_appt_date",
            new_name="hiv_clinic_next_appt_date",
        ),
        migrations.RenameField(
            model_name="baselinecarestatus",
            old_name="hiv_willing_to_transfer",
            new_name="hiv_clinic_willing_to_transfer",
        ),
        migrations.RenameField(
            model_name="baselinecarestatus",
            old_name="ncd_next_appt_date",
            new_name="ncd_clinic_next_appt_date",
        ),
        migrations.RenameField(
            model_name="baselinecarestatus",
            old_name="ncd_willing_to_transfer",
            new_name="ncd_clinic_willing_to_transfer",
        ),
        migrations.RenameField(
            model_name="baselinecarestatus",
            old_name="attending_hiv_clinic",
            new_name="receive_care_at_hiv_clinic",
        ),
        migrations.RenameField(
            model_name="baselinecarestatus",
            old_name="attending_ncd_clinic",
            new_name="receive_care_at_ncd_clinic",
        ),
        migrations.RenameField(
            model_name="historicalbaselinecarestatus",
            old_name="hiv_next_appt_date",
            new_name="hiv_clinic_next_appt_date",
        ),
        migrations.RenameField(
            model_name="historicalbaselinecarestatus",
            old_name="hiv_willing_to_transfer",
            new_name="hiv_clinic_willing_to_transfer",
        ),
        migrations.RenameField(
            model_name="historicalbaselinecarestatus",
            old_name="ncd_next_appt_date",
            new_name="ncd_clinic_next_appt_date",
        ),
        migrations.RenameField(
            model_name="historicalbaselinecarestatus",
            old_name="ncd_willing_to_transfer",
            new_name="ncd_clinic_willing_to_transfer",
        ),
        migrations.RenameField(
            model_name="historicalbaselinecarestatus",
            old_name="attending_hiv_clinic",
            new_name="receive_care_at_hiv_clinic",
        ),
        migrations.RenameField(
            model_name="historicalbaselinecarestatus",
            old_name="attending_ncd_clinic",
            new_name="receive_care_at_ncd_clinic",
        ),
    ]
