# Generated by Django 2.2.10 on 2020-02-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0012_auto_20200224_2134"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baselinecarestatus",
            old_name="use_hiv_clinic_nearby",
            new_name="attends_this_hiv_clinic",
        ),
        migrations.RenameField(
            model_name="baselinecarestatus",
            old_name="use_ncd_clinic_nearby",
            new_name="attends_this_ncd_clinic",
        ),
        migrations.RenameField(
            model_name="historicalbaselinecarestatus",
            old_name="use_hiv_clinic_nearby",
            new_name="attends_this_hiv_clinic",
        ),
        migrations.RenameField(
            model_name="historicalbaselinecarestatus",
            old_name="use_ncd_clinic_nearby",
            new_name="attends_this_ncd_clinic",
        ),
    ]
