# Generated by Django 2.2.10 on 2020-02-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0013_auto_20200224_2242"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baselinecarestatus",
            old_name="receive_care_at_hiv_clinic",
            new_name="receives_care_at_hiv_clinic",
        ),
        migrations.RenameField(
            model_name="baselinecarestatus",
            old_name="receive_care_at_ncd_clinic",
            new_name="receives_care_at_ncd_clinic",
        ),
        migrations.RenameField(
            model_name="historicalbaselinecarestatus",
            old_name="receive_care_at_hiv_clinic",
            new_name="receives_care_at_hiv_clinic",
        ),
        migrations.RenameField(
            model_name="historicalbaselinecarestatus",
            old_name="receive_care_at_ncd_clinic",
            new_name="receives_care_at_ncd_clinic",
        ),
    ]
