# Generated by Django 3.0.6 on 2020-07-02 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_lists", "0005_auto_20200701_0041"),
        ("inte_subject", "0014_auto_20200701_0740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drugrefillhiv",
            name="purchased_days",
            field=models.IntegerField(
                help_text="This can be purchased by patient, through a medicines club that the patient belong to, through insurance or someone else has paid. ",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="How many days supplied by to be purchased",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldrugrefillhiv",
            name="purchased_days",
            field=models.IntegerField(
                help_text="This can be purchased by patient, through a medicines club that the patient belong to, through insurance or someone else has paid. ",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="How many days supplied by to be purchased",
            ),
        ),
        migrations.AlterField(
            model_name="reasonforvisit",
            name="clinic_services",
            field=models.ManyToManyField(
                related_name="clinic_services",
                to="inte_lists.ClinicServices",
                verbose_name="Why is the patient at the clinic?",
            ),
        ),
    ]
