# Generated by Django 3.0 on 2020-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0014_auto_20200224_2250"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphysicalactivity",
            name="physical_activity",
            field=models.CharField(
                choices=[
                    ("retired", "Retired"),
                    ("sitting", "Mostly sitting"),
                    ("standing_or_walking", "Mostly standing or walking"),
                    ("physical_effort", "Definite physical effort"),
                    ("vigorous_physical_activity", "Vigorous physical activity"),
                ],
                help_text="Please tick one box that is closest to your present work from the following five possibilities",
                max_length=50,
                verbose_name="Please tell us the type and amount of physical activity involved in your work.",
            ),
        ),
        migrations.AlterField(
            model_name="physicalactivity",
            name="physical_activity",
            field=models.CharField(
                choices=[
                    ("retired", "Retired"),
                    ("sitting", "Mostly sitting"),
                    ("standing_or_walking", "Mostly standing or walking"),
                    ("physical_effort", "Definite physical effort"),
                    ("vigorous_physical_activity", "Vigorous physical activity"),
                ],
                help_text="Please tick one box that is closest to your present work from the following five possibilities",
                max_length=50,
                verbose_name="Please tell us the type and amount of physical activity involved in your work.",
            ),
        ),
    ]
