# Generated by Django 3.0.5 on 2020-04-04 14:44

from django.db import migrations, models
import edc_model.models.fields.blood_pressure


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0016_auto_20200404_1720"),
    ]

    operations = [
        migrations.AddField(
            model_name="anthropometry",
            name="r2_taken",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Was a <u>second</u> blood pressure reading taken",
            ),
        ),
        migrations.AddField(
            model_name="historicalanthropometry",
            name="r2_taken",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Was a <u>second</u> blood pressure reading taken",
            ),
        ),
        migrations.AlterField(
            model_name="anthropometry",
            name="dia_blood_pressure_r2",
            field=edc_model.models.fields.blood_pressure.DiastolicPressureField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="anthropometry",
            name="sys_blood_pressure_r2",
            field=edc_model.models.fields.blood_pressure.SystolicPressureField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="baselinecarestatus",
            name="ncd_clinic_other",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="If not attending the NCD clinic in <u>this facility</u>, where do you attend?",
            ),
        ),
        migrations.AlterField(
            model_name="baselinecarestatus",
            name="ncd_clinic_other_is_study_clinic",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="If not attending the NCD clinic in <u>this facility</u>, is the NCD clinic an INTE study clinic?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalanthropometry",
            name="dia_blood_pressure_r2",
            field=edc_model.models.fields.blood_pressure.DiastolicPressureField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalanthropometry",
            name="sys_blood_pressure_r2",
            field=edc_model.models.fields.blood_pressure.SystolicPressureField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalbaselinecarestatus",
            name="ncd_clinic_other",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="If not attending the NCD clinic in <u>this facility</u>, where do you attend?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbaselinecarestatus",
            name="ncd_clinic_other_is_study_clinic",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="If not attending the NCD clinic in <u>this facility</u>, is the NCD clinic an INTE study clinic?",
            ),
        ),
    ]
