# Generated by Django 3.0.6 on 2020-07-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0017_auto_20200709_0823"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalhivinitialreview",
            name="vl_quantifier",
            field=models.CharField(
                blank=True,
                choices=[("=", "="), (">", ">"), ("<", "<")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hivinitialreview",
            name="vl_quantifier",
            field=models.CharField(
                blank=True,
                choices=[("=", "="), (">", ">"), ("<", "<")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhivinitialreview",
            name="has_vl",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("PENDING", "Pending"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=25,
                verbose_name="Is the patient's most recent viral load result available?",
            ),
        ),
        migrations.AlterField(
            model_name="hivinitialreview",
            name="has_vl",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("PENDING", "Pending"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=25,
                verbose_name="Is the patient's most recent viral load result available?",
            ),
        ),
    ]
