# Generated by Django 3.0.6 on 2020-07-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_lists", "0005_auto_20200701_0041"),
        ("inte_subject", "0019_auto_20200714_1654"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigations",
            name="reason",
            field=models.ManyToManyField(
                blank=True,
                to="inte_lists.ReasonsForTesting",
                verbose_name="Why was the patient tested?",
            ),
        ),
    ]
