# Generated by Django 3.0.4 on 2020-04-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0019_auto_20200404_1814"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diabetesinitialreview",
            name="on_treatment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Is the patient currently taking medicines for control?",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicaldiabetesinitialreview",
            name="on_treatment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Is the patient currently taking medicines for control?",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalhivinitialreview",
            name="on_treatment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Is the patient currently taking medicines for control?",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalhypertensioninitialreview",
            name="on_treatment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Is the patient currently taking medicines for control?",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hivinitialreview",
            name="on_treatment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Is the patient currently taking medicines for control?",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hypertensioninitialreview",
            name="on_treatment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Is the patient currently taking medicines for control?",
            ),
            preserve_default=False,
        ),
    ]
