# Generated by Django 3.0.4 on 2020-04-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0021_auto_20200404_1849"),
    ]

    operations = [
        migrations.AddField(
            model_name="diabetesinitialreview",
            name="glucose_measurement_reason_not_taken",
            field=models.TextField(
                max_length=250,
                null=True,
                verbose_name="If the glucose measurement was not taken, explain?",
            ),
        ),
        migrations.AddField(
            model_name="diabetesinitialreview",
            name="glucose_measurement_taken",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Was a glucose measurement taken?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaldiabetesinitialreview",
            name="glucose_measurement_reason_not_taken",
            field=models.TextField(
                max_length=250,
                null=True,
                verbose_name="If the glucose measurement was not taken, explain?",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiabetesinitialreview",
            name="glucose_measurement_taken",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Was a glucose measurement taken?",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="diabetesinitialreview",
            name="fasted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                max_length=15,
                null=True,
                verbose_name="Has the participant fasted?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiabetesinitialreview",
            name="fasted",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                max_length=15,
                null=True,
                verbose_name="Has the participant fasted?",
            ),
        ),
    ]
