# Generated by Django 3.0.6 on 2020-07-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0021_auto_20200730_0710"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healtheconomics",
            name="diabetic_expenditure_month",
            field=models.IntegerField(
                blank=True,
                help_text="in Shilling",
                null=True,
                verbose_name="If YES, how much did you spend on Diabetic drugs",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomics",
            name="diabetic_payee",
            field=models.CharField(
                choices=[
                    ("own_cash", "Own cash"),
                    ("insurance", "Insurance"),
                    ("relative", "Relative of others paying"),
                    ("free", "Free drugs from the pharmacy"),
                    ("N/A", "Not applicable"),
                ],
                max_length=15,
                verbose_name="If YES, how did you pay or who paid for these drugs",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomics",
            name="diabetic_expenditure_month",
            field=models.IntegerField(
                blank=True,
                help_text="in Shilling",
                null=True,
                verbose_name="If YES, how much did you spend on Diabetic drugs",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomics",
            name="diabetic_payee",
            field=models.CharField(
                choices=[
                    ("own_cash", "Own cash"),
                    ("insurance", "Insurance"),
                    ("relative", "Relative of others paying"),
                    ("free", "Free drugs from the pharmacy"),
                    ("N/A", "Not applicable"),
                ],
                max_length=15,
                verbose_name="If YES, how did you pay or who paid for these drugs",
            ),
        ),
    ]
