# Generated by Django 3.0.4 on 2020-04-04 16:57

from django.db import migrations
import edc_model.models.fields.other_charfield


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0023_auto_20200404_1930"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalhypertensioninitialreview",
            name="other_treatment",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="hypertensioninitialreview",
            name="other_treatment",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
    ]
