# Generated by Django 3.0.6 on 2020-08-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0026_auto_20200812_2240"),
    ]

    operations = [
        migrations.RenameField(
            model_name="healtheconomicsrevised",
            old_name="rx_arv_cost_today",
            new_name="rx_hiv_cost_today",
        ),
        migrations.RenameField(
            model_name="historicalhealtheconomicsrevised",
            old_name="rx_arv_cost_today",
            new_name="rx_hiv_cost_today",
        ),
    ]
