# Generated by Django 3.0.4 on 2020-04-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0026_auto_20200404_2055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthriskassessment",
            name="smoker_quit_ago_months",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhealthriskassessment",
            name="smoker_quit_ago_months",
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
