# Generated by Django 3.0.6 on 2020-08-13 15:17

import edc_model.models.fields.other_charfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0028_auto_20200813_1736"),
    ]

    operations = [
        migrations.RenameField(
            model_name="healtheconomicsrevised",
            old_name="non_drug_activities_cost",
            new_name="non_drug_activities_month_cost",
        ),
        migrations.RenameField(
            model_name="healtheconomicsrevised",
            old_name="non_drug_activities_detail",
            new_name="non_drug_activities_month_detail",
        ),
        migrations.RenameField(
            model_name="historicalhealtheconomicsrevised",
            old_name="non_drug_activities_cost",
            new_name="non_drug_activities_month_cost",
        ),
        migrations.RenameField(
            model_name="historicalhealtheconomicsrevised",
            old_name="non_drug_activities_detail",
            new_name="non_drug_activities_month_detail",
        ),
        migrations.AddField(
            model_name="healtheconomicsrevised",
            name="childcare_source_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="historicalhealtheconomicsrevised",
            name="childcare_source_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomics",
            name="childcare_source",
            field=models.CharField(
                choices=[
                    ("working", "Working"),
                    ("studying", "Studying"),
                    ("caring_for_children", "Caring for children"),
                    ("house_maintenance", "House maintenance"),
                    ("nothing", "Nothing"),
                    ("OTHER", "Other, specify"),
                ],
                default="N/A",
                max_length=25,
                verbose_name="If Yes, what would they have been doing if they had not stayed to look after your child or children?",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomicsrevised",
            name="childcare",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Did you ask anyone else, such as your family member/friend to look after your child/children in order to come here?",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomicsrevised",
            name="childcare_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("working", "Working"),
                    ("studying", "Studying"),
                    ("caring_for_children", "Caring for children"),
                    ("house_maintenance", "House maintenance"),
                    ("nothing", "Nothing"),
                    ("OTHER", "Other, specify"),
                ],
                max_length=25,
                null=True,
                verbose_name="If Yes, what would they have been doing if they had not stayed to look after your child or children?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomics",
            name="childcare_source",
            field=models.CharField(
                choices=[
                    ("working", "Working"),
                    ("studying", "Studying"),
                    ("caring_for_children", "Caring for children"),
                    ("house_maintenance", "House maintenance"),
                    ("nothing", "Nothing"),
                    ("OTHER", "Other, specify"),
                ],
                default="N/A",
                max_length=25,
                verbose_name="If Yes, what would they have been doing if they had not stayed to look after your child or children?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsrevised",
            name="childcare",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Did you ask anyone else, such as your family member/friend to look after your child/children in order to come here?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsrevised",
            name="childcare_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("working", "Working"),
                    ("studying", "Studying"),
                    ("caring_for_children", "Caring for children"),
                    ("house_maintenance", "House maintenance"),
                    ("nothing", "Nothing"),
                    ("OTHER", "Other, specify"),
                ],
                max_length=25,
                null=True,
                verbose_name="If Yes, what would they have been doing if they had not stayed to look after your child or children?",
            ),
        ),
    ]
