# Generated by Django 3.0.9 on 2020-08-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0031_auto_20200818_1847"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectvisit",
            name="info_source",
            field=models.CharField(
                choices=[
                    ("hospital_notes", "Hospital notes"),
                    ("outpatient_cards", "Outpatient cards"),
                    ("patient", "Patient"),
                    (
                        "patient_and_outpatient",
                        "Patient, hospital notes and/or outpatient card",
                    ),
                    ("collateral_history", "Collateral History from relative/guardian"),
                    ("OTHER", "Other"),
                ],
                max_length=25,
                verbose_name="What is the main source of this information?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectvisit",
            name="info_source",
            field=models.CharField(
                choices=[
                    ("hospital_notes", "Hospital notes"),
                    ("outpatient_cards", "Outpatient cards"),
                    ("patient", "Patient"),
                    (
                        "patient_and_outpatient",
                        "Patient, hospital notes and/or outpatient card",
                    ),
                    ("collateral_history", "Collateral History from relative/guardian"),
                    ("OTHER", "Other"),
                ],
                max_length=25,
                verbose_name="What is the main source of this information?",
            ),
        ),
    ]
