# Generated by Django 3.0.9 on 2020-08-20 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inte_subject", "0033_auto_20200820_2008"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CareStatusBaseline",
            new_name="ClinicalReviewBaseline",
        ),
        migrations.RenameModel(
            old_name="HistoricalCareStatusBaseline",
            new_name="HistoricalClinicalReviewBaseline",
        ),
        migrations.RemoveIndex(
            model_name="clinicalreviewbaseline",
            name="inte_subjec_subject_bf51eb_idx",
        ),
        migrations.AddIndex(
            model_name="clinicalreviewbaseline",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="inte_subjec_subject_d5d260_idx",
            ),
        ),
    ]
