# Generated by Django 3.0.9 on 2020-08-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0036_auto_20200823_2157"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clinicalreviewbaseline",
            old_name="diabetes",
            new_name="diabetes_dx",
        ),
        migrations.RenameField(
            model_name="clinicalreviewbaseline",
            old_name="hypertension",
            new_name="hypertension_dx",
        ),
        migrations.RenameField(
            model_name="historicalclinicalreviewbaseline",
            old_name="diabetes",
            new_name="diabetes_dx",
        ),
        migrations.RenameField(
            model_name="historicalclinicalreviewbaseline",
            old_name="hypertension",
            new_name="hypertension_dx",
        ),
        migrations.AddField(
            model_name="clinicalreviewbaseline",
            name="hiv_dx",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                editable=False,
                max_length=15,
                null=True,
                verbose_name="Was the patient diagnosed with HIV infection?",
            ),
        ),
        migrations.AddField(
            model_name="historicalclinicalreviewbaseline",
            name="hiv_dx",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                editable=False,
                max_length=15,
                null=True,
                verbose_name="Was the patient diagnosed with HIV infection?",
            ),
        ),
    ]
