# Generated by Django 3.0.9 on 2020-08-23 23:25

import edc_model.models.validators.date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0038_auto_20200824_0120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalreviewbaseline",
            name="diabetes_tested_estimated_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="calculated by the EDC using `diabetes_tested_ago`",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreviewbaseline",
            name="hiv_tested_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.models.validators.date.date_not_future],
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreviewbaseline",
            name="hiv_tested_estimated_datetime",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="calculated by the EDC using `hiv_tested_ago`",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreviewbaseline",
            name="hypertension_tested_estimated_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="calculated by the EDC using `hypertension_tested_ago`",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicalreviewbaseline",
            name="diabetes_tested_estimated_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="calculated by the EDC using `diabetes_tested_ago`",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicalreviewbaseline",
            name="hiv_tested_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.models.validators.date.date_not_future],
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicalreviewbaseline",
            name="hiv_tested_estimated_datetime",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="calculated by the EDC using `hiv_tested_ago`",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicalreviewbaseline",
            name="hypertension_tested_estimated_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="calculated by the EDC using `hypertension_tested_ago`",
                null=True,
            ),
        ),
    ]
