# Generated by Django 3.0.9 on 2020-08-26 18:48
from django.db import migrations

from inte_subject.update_appointment_schedule import update_appointment_schedule


def update_appointments(apps, schema_editor):
    update_appointment_schedule(apps)


class Migration(migrations.Migration):

    dependencies = [
        ("edc_appointment", "0024_auto_20200911_0425"),
        ("inte_subject", "0042_auto_20200826_1924"),
    ]

    operations = [migrations.RunPython(update_appointments)]
