# Generated by Django 3.0.9 on 2020-09-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_lists", "0007_auto_20200910_1742"),
        ("inte_subject", "0049_auto_20200910_1904"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalreviewbaseline",
            name="hiv_dx",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                max_length=15,
                null=True,
                verbose_name="Has the patient ever tested positive for HIV?",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalreviewbaseline",
            name="hiv_test",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                help_text="If positive, complete form `Hiv Initial Review`",
                max_length=15,
                verbose_name="What was the result of the patient's most recent HIV test",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicalreviewbaseline",
            name="hiv_dx",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                max_length=15,
                null=True,
                verbose_name="Has the patient ever tested positive for HIV?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinicalreviewbaseline",
            name="hiv_test",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                help_text="If positive, complete form `Hiv Initial Review`",
                max_length=15,
                verbose_name="What was the result of the patient's most recent HIV test",
            ),
        ),
    ]
