# Generated by Django 3.0.9 on 2020-09-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_lists", "0007_auto_20200910_1742"),
        ("inte_subject", "0055_auto_20200912_1751"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complicationsbaseline",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
                "verbose_name": "Complications: Baseline",
                "verbose_name_plural": "Complications: Baseline",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcomplicationsbaseline",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Complications: Baseline",
            },
        ),
        migrations.RemoveIndex(
            model_name="complicationsbaseline",
            name="inte_subjec_subject_5de7e3_idx",
        ),
        migrations.AlterField(
            model_name="complicationsbaseline",
            name="foot_ulcers",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=25,
                null=True,
                verbose_name="Foot ulcers",
            ),
        ),
        migrations.AlterField(
            model_name="complicationsbaseline",
            name="heart_attack",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=25,
                null=True,
                verbose_name="Heart attack / heart failure",
            ),
        ),
        migrations.AlterField(
            model_name="complicationsbaseline",
            name="numbness",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=25,
                null=True,
                verbose_name="Numbness / burning sensation",
            ),
        ),
        migrations.AlterField(
            model_name="complicationsbaseline",
            name="renal_disease",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=25,
                null=True,
                verbose_name="Renal (kidney) disease",
            ),
        ),
        migrations.AlterField(
            model_name="complicationsbaseline",
            name="stroke",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=25,
                null=True,
                verbose_name="Stroke",
            ),
        ),
        migrations.AlterField(
            model_name="complicationsbaseline",
            name="vision",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=25,
                null=True,
                verbose_name="Vision problems (e.g. blurred vision)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplicationsbaseline",
            name="foot_ulcers",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=25,
                null=True,
                verbose_name="Foot ulcers",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplicationsbaseline",
            name="heart_attack",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=25,
                null=True,
                verbose_name="Heart attack / heart failure",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplicationsbaseline",
            name="numbness",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=25,
                null=True,
                verbose_name="Numbness / burning sensation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplicationsbaseline",
            name="renal_disease",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=25,
                null=True,
                verbose_name="Renal (kidney) disease",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplicationsbaseline",
            name="stroke",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=25,
                null=True,
                verbose_name="Stroke",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomplicationsbaseline",
            name="vision",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=25,
                null=True,
                verbose_name="Vision problems (e.g. blurred vision)",
            ),
        ),
        migrations.AddIndex(
            model_name="complicationsbaseline",
            index=models.Index(
                fields=["subject_visit", "site", "id"],
                name="inte_subjec_subject_246b6c_idx",
            ),
        ),
    ]
