# Generated by Django 3.0.9 on 2020-09-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0058_auto_20200912_1804"),
    ]

    operations = []
