# Generated by Django 3.0.9 on 2020-09-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0059_auto_20200913_2356"),
    ]

    operations = []
