# Generated by Django 3.0.9 on 2020-09-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0060_auto_20200914_1858"),
    ]

    operations = []
