# Generated by Django 3.0.9 on 2020-09-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inte_lists', '0007_auto_20200910_1742'),
        ('inte_subject', '0061_auto_20200915_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvestigations',
            name='diabetes_dx',
        ),
        migrations.RemoveField(
            model_name='historicalinvestigations',
            name='diabetes_reason_other',
        ),
        migrations.RemoveField(
            model_name='historicalinvestigations',
            name='hiv_dx',
        ),
        migrations.RemoveField(
            model_name='historicalinvestigations',
            name='hiv_reason_other',
        ),
        migrations.RemoveField(
            model_name='historicalinvestigations',
            name='hypertension_dx',
        ),
        migrations.RemoveField(
            model_name='historicalinvestigations',
            name='hypertension_reason_other',
        ),
        migrations.RemoveField(
            model_name='investigations',
            name='diabetes_dx',
        ),
        migrations.RemoveField(
            model_name='investigations',
            name='diabetes_reason',
        ),
        migrations.RemoveField(
            model_name='investigations',
            name='diabetes_reason_other',
        ),
        migrations.RemoveField(
            model_name='investigations',
            name='hiv_dx',
        ),
        migrations.RemoveField(
            model_name='investigations',
            name='hiv_reason',
        ),
        migrations.RemoveField(
            model_name='investigations',
            name='hiv_reason_other',
        ),
        migrations.RemoveField(
            model_name='investigations',
            name='hypertension_dx',
        ),
        migrations.RemoveField(
            model_name='investigations',
            name='hypertension_reason',
        ),
        migrations.RemoveField(
            model_name='investigations',
            name='hypertension_reason_other',
        ),
        migrations.AlterField(
            model_name='clinicalreview',
            name='dm_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text="Note: Select `not applicable` if diagnosis previously reported. <BR>`Since last seen` includes today.<BR>If `yes', complete the initial review CRF<BR>If `not applicable`, complete the review CRF.", max_length=15, verbose_name='Since last seen, was the patient tested for diabetes?'),
        ),
        migrations.AlterField(
            model_name='clinicalreview',
            name='hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text="Note: Select `not applicable` if diagnosis previously reported. <BR>`Since last seen` includes today.<BR>If `yes', complete the initial review CRF<BR>If `not applicable`, complete the review CRF.", max_length=15, verbose_name='Since last seen, was the patient tested for HIV infection?'),
        ),
        migrations.AlterField(
            model_name='clinicalreview',
            name='htn_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text="Note: Select `not applicable` if diagnosis previously reported. <BR>`Since last seen` includes today.<BR>If `yes', complete the initial review CRF<BR>If `not applicable`, complete the review CRF.", max_length=15, verbose_name='Since last seen, was the patient tested for hypertension?'),
        ),
        migrations.AlterField(
            model_name='clinicalreviewbaseline',
            name='hiv_dx',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text='If yes, complete form `HIV Initial Review`', max_length=15, verbose_name='Has the patient ever tested <U>positive</U> for HIV infection?'),
        ),
        migrations.AlterField(
            model_name='clinicalreviewbaseline',
            name='hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15, verbose_name='Has the patient ever tested for HIV infection?'),
        ),
        migrations.AlterField(
            model_name='historicalclinicalreview',
            name='dm_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text="Note: Select `not applicable` if diagnosis previously reported. <BR>`Since last seen` includes today.<BR>If `yes', complete the initial review CRF<BR>If `not applicable`, complete the review CRF.", max_length=15, verbose_name='Since last seen, was the patient tested for diabetes?'),
        ),
        migrations.AlterField(
            model_name='historicalclinicalreview',
            name='hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text="Note: Select `not applicable` if diagnosis previously reported. <BR>`Since last seen` includes today.<BR>If `yes', complete the initial review CRF<BR>If `not applicable`, complete the review CRF.", max_length=15, verbose_name='Since last seen, was the patient tested for HIV infection?'),
        ),
        migrations.AlterField(
            model_name='historicalclinicalreview',
            name='htn_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text="Note: Select `not applicable` if diagnosis previously reported. <BR>`Since last seen` includes today.<BR>If `yes', complete the initial review CRF<BR>If `not applicable`, complete the review CRF.", max_length=15, verbose_name='Since last seen, was the patient tested for hypertension?'),
        ),
        migrations.AlterField(
            model_name='historicalclinicalreviewbaseline',
            name='hiv_dx',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text='If yes, complete form `HIV Initial Review`', max_length=15, verbose_name='Has the patient ever tested <U>positive</U> for HIV infection?'),
        ),
        migrations.AlterField(
            model_name='historicalclinicalreviewbaseline',
            name='hiv_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15, verbose_name='Has the patient ever tested for HIV infection?'),
        ),
        migrations.AlterField(
            model_name='historicalinvestigations',
            name='diabetes_tested',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=15, verbose_name='Was the patient tested for diabetes?'),
        ),
        migrations.AlterField(
            model_name='historicalinvestigations',
            name='hiv_tested',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=15, verbose_name='Was the patient tested for HIV infection?'),
        ),
        migrations.AlterField(
            model_name='historicalinvestigations',
            name='hypertension_tested',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=15, verbose_name='Was the patient tested for hypertension?'),
        ),
        migrations.AlterField(
            model_name='historicalinvestigations',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date test requested'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='diabetes_tested',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=15, verbose_name='Was the patient tested for diabetes?'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='hiv_tested',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=15, verbose_name='Was the patient tested for HIV infection?'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='hypertension_tested',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=15, verbose_name='Was the patient tested for hypertension?'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='reason',
            field=models.ManyToManyField(blank=True, to='inte_lists.ReasonsForTesting', verbose_name='Why was the patient tested?'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date test requested'),
        ),
    ]
