# Generated by Django 3.0.9 on 2020-09-26 20:19

import edc_model.models.fields.other_charfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0065_auto_20200926_2304"),
    ]

    operations = [
        migrations.AddField(
            model_name="healtheconomicsrevised",
            name="rx_dm_paid_today_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="healtheconomicsrevised",
            name="rx_hiv_paid_today_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="healtheconomicsrevised",
            name="rx_htn_paid_today_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="healtheconomicsrevised",
            name="rx_other_paid_today_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="historicalhealtheconomicsrevised",
            name="rx_dm_paid_today_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="historicalhealtheconomicsrevised",
            name="rx_hiv_paid_today_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="historicalhealtheconomicsrevised",
            name="rx_htn_paid_today_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ...",
            ),
        ),
        migrations.AddField(
            model_name="historicalhealtheconomicsrevised",
            name="rx_other_paid_today_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomicsrevised",
            name="rx_dm_paid_month_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ... (DM)",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomicsrevised",
            name="rx_hiv_paid_month_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ... (HIV)",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomicsrevised",
            name="rx_htn_paid_month_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ...(HTN)",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomicsrevised",
            name="rx_other_month",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Did you receive any 'other' drugs?",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomicsrevised",
            name="rx_other_paid_month_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomicsrevised",
            name="transport_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other reason`, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsrevised",
            name="rx_dm_paid_month_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ... (DM)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsrevised",
            name="rx_hiv_paid_month_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ... (HIV)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsrevised",
            name="rx_htn_paid_month_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ...(HTN)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsrevised",
            name="rx_other_month",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Did you receive any 'other' drugs?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsrevised",
            name="rx_other_paid_month_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other pay source`, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsrevised",
            name="transport_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If `other reason`, please specify ...",
            ),
        ),
    ]
