# Generated by Django 3.0.9 on 2020-10-02 17:42

import edc_model.models.fields.duration
import edc_model.models.fields.initials_field
import edc_model.models.fields.other_charfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_lists", "0008_auto_20201002_0403"),
        ("inte_subject", "0068_auto_20201002_0403"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalreviewbaseline",
            name="dm_test_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clinicalreviewbaseline",
            name="hiv_test_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clinicalreviewbaseline",
            name="htn_test_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="complicationsbaseline",
            name="foot_ulcers_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="complicationsbaseline",
            name="heart_attack_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="complicationsbaseline",
            name="numbness_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="complicationsbaseline",
            name="renal_disease_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="complicationsbaseline",
            name="stroke_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="complicationsbaseline",
            name="vision_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dminitialreview",
            name="dx_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dminitialreview",
            name="med_start_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalclinicalreviewbaseline",
            name="dm_test_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalclinicalreviewbaseline",
            name="hiv_test_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalclinicalreviewbaseline",
            name="htn_test_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcomplicationsbaseline",
            name="foot_ulcers_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcomplicationsbaseline",
            name="heart_attack_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcomplicationsbaseline",
            name="numbness_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcomplicationsbaseline",
            name="renal_disease_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcomplicationsbaseline",
            name="stroke_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcomplicationsbaseline",
            name="vision_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldminitialreview",
            name="dx_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldminitialreview",
            name="med_start_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhivinitialreview",
            name="arv_initiation_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhivinitialreview",
            name="dx_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhtninitialreview",
            name="dx_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalhtninitialreview",
            name="med_start_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalotherbaselinedata",
            name="smoker_quit_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalsubjectrequisition",
            name="clinician_initials",
            field=edc_model.models.fields.initials_field.InitialsField(
                blank=True,
                help_text="Type 2-3 letters, all in uppercase and no spaces",
                max_length=3,
                null=True,
                verbose_name="Initials",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectrequisition",
            name="reason_not_drawn_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
        migrations.AlterField(
            model_name="hivinitialreview",
            name="arv_initiation_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hivinitialreview",
            name="dx_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="htninitialreview",
            name="dx_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="htninitialreview",
            name="med_start_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="otherbaselinedata",
            name="smoker_quit_ago",
            field=edc_model.models.fields.duration.DurationYMDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subjectrequisition",
            name="clinician_initials",
            field=edc_model.models.fields.initials_field.InitialsField(
                blank=True,
                help_text="Type 2-3 letters, all in uppercase and no spaces",
                max_length=3,
                null=True,
                verbose_name="Initials",
            ),
        ),
        migrations.AlterField(
            model_name="subjectrequisition",
            name="reason_not_drawn_other",
            field=edc_model.models.fields.other_charfield.OtherCharField(
                blank=True,
                max_length=35,
                null=True,
                verbose_name="If other, please specify ...",
            ),
        ),
    ]
