# Generated by Django 3.0.9 on 2020-10-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_lists", "0008_auto_20201002_0403"),
        ("inte_subject", "0071_auto_20201006_2051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healtheconomicsrevised",
            name="rx_dm_today",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Did you receive drugs for raised blood sugar (diabetes) today?",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomicsrevised",
            name="rx_hiv_today",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Did you receive ARVs (HIV) today?",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomicsrevised",
            name="rx_htn_today",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Did you receive raised blood pressure (hypertension) drugs today?",
            ),
        ),
        migrations.AlterField(
            model_name="healtheconomicsrevised",
            name="rx_other_month",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=15,
                verbose_name="Did you receive any 'other' drugs?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsrevised",
            name="rx_dm_today",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Did you receive drugs for raised blood sugar (diabetes) today?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsrevised",
            name="rx_hiv_today",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Did you receive ARVs (HIV) today?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsrevised",
            name="rx_htn_today",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Did you receive raised blood pressure (hypertension) drugs today?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsrevised",
            name="rx_other_month",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=15,
                verbose_name="Did you receive any 'other' drugs?",
            ),
        ),
    ]
