# Generated by Django 3.0.9 on 2020-10-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_lists", "0008_auto_20201002_0403"),
        ("inte_subject", "0074_auto_20201021_0132"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalinvestigations",
            name="diabetes_dx",
        ),
        migrations.RemoveField(
            model_name="historicalinvestigations",
            name="diabetes_reason_other",
        ),
        migrations.RemoveField(
            model_name="historicalinvestigations",
            name="hiv_dx",
        ),
        migrations.RemoveField(
            model_name="historicalinvestigations",
            name="hiv_reason_other",
        ),
        migrations.RemoveField(
            model_name="historicalinvestigations",
            name="hypertension_dx",
        ),
        migrations.RemoveField(
            model_name="historicalinvestigations",
            name="hypertension_reason_other",
        ),
        migrations.RemoveField(
            model_name="investigations",
            name="diabetes_dx",
        ),
        migrations.RemoveField(
            model_name="investigations",
            name="diabetes_reason",
        ),
        migrations.RemoveField(
            model_name="investigations",
            name="diabetes_reason_other",
        ),
        migrations.RemoveField(
            model_name="investigations",
            name="hiv_dx",
        ),
        migrations.RemoveField(
            model_name="investigations",
            name="hiv_reason",
        ),
        migrations.RemoveField(
            model_name="investigations",
            name="hiv_reason_other",
        ),
        migrations.RemoveField(
            model_name="investigations",
            name="hypertension_dx",
        ),
        migrations.RemoveField(
            model_name="investigations",
            name="hypertension_reason",
        ),
        migrations.RemoveField(
            model_name="investigations",
            name="hypertension_reason_other",
        ),
        migrations.AlterField(
            model_name="historicalinvestigations",
            name="diabetes_tested",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=15,
                verbose_name="Was the patient tested for diabetes?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvestigations",
            name="hiv_tested",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=15,
                verbose_name="Was the patient tested for HIV infection?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvestigations",
            name="hypertension_tested",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=15,
                verbose_name="Was the patient tested for hypertension?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvestigations",
            name="test_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date test requested"),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="diabetes_tested",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=15,
                verbose_name="Was the patient tested for diabetes?",
            ),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="hiv_tested",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=15,
                verbose_name="Was the patient tested for HIV infection?",
            ),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="hypertension_tested",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=15,
                verbose_name="Was the patient tested for hypertension?",
            ),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="reason",
            field=models.ManyToManyField(
                blank=True,
                to="inte_lists.ReasonsForTesting",
                verbose_name="Why was the patient tested?",
            ),
        ),
        migrations.AlterField(
            model_name="investigations",
            name="test_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date test requested"),
        ),
    ]
