# Generated by Django 3.0.9 on 2020-11-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0075_auto_20201021_1853"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalnextappointment",
            name="integrated_clinic_appt_date",
            field=models.DateField(
                blank=True,
                help_text="if applicable.",
                null=True,
                verbose_name="Integrated clinic: next scheduled routine appointment",
            ),
        ),
        migrations.AddField(
            model_name="nextappointment",
            name="integrated_clinic_appt_date",
            field=models.DateField(
                blank=True,
                help_text="if applicable.",
                null=True,
                verbose_name="Integrated clinic: next scheduled routine appointment",
            ),
        ),
    ]
