# Generated by Django 3.2.3 on 2021-05-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_lists", "0011_auto_20210524_1533"),
        ("inte_subject", "0081_auto_20210524_1921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalintegratedcarereview",
            name="additional_health_advice",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Did you receive any additional health advice during your visit?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalintegratedcarereview",
            name="receive_health_talk_messages",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Did you receive health talks when attending the clinic today?",
            ),
        ),
        migrations.AlterField(
            model_name="integratedcarereview",
            name="additional_health_advice",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Did you receive any additional health advice during your visit?",
            ),
        ),
        migrations.AlterField(
            model_name="integratedcarereview",
            name="health_talk_conditions",
            field=models.ManyToManyField(
                blank=True,
                related_name="_inte_subject_integratedcarereview_health_talk_conditions_+",
                to="inte_lists.HealthTalkConditions",
                verbose_name="If YES, what disease conditions were discussed during the health talk?",
            ),
        ),
        migrations.AlterField(
            model_name="integratedcarereview",
            name="health_talk_focus",
            field=models.ManyToManyField(
                blank=True,
                related_name="_inte_subject_integratedcarereview_health_talk_focus_+",
                to="inte_lists.HealthInterventionTypes",
                verbose_name="If YES, what type of messages were covered during the health talk?",
            ),
        ),
        migrations.AlterField(
            model_name="integratedcarereview",
            name="health_talk_presenters",
            field=models.ManyToManyField(
                blank=True,
                related_name="_inte_subject_integratedcarereview_health_talk_presenters_+",
                to="inte_lists.HealthAdvisors",
                verbose_name="If YES, who gave the health talk?",
            ),
        ),
        migrations.AlterField(
            model_name="integratedcarereview",
            name="receive_health_talk_messages",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=15,
                verbose_name="Did you receive health talks when attending the clinic today?",
            ),
        ),
    ]
