# Generated by Django 3.2.3 on 2021-05-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inte_subject", "0084_auto_20210526_1640"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arvregimens",
            options={"verbose_name": "ARV Regimens", "verbose_name_plural": "ARV Regimens"},
        ),
    ]
