# Generated by Django 3.2.13 on 2022-06-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inte_subject', '0087_auto_20220608_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalhba1cresult',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical HbA1c Result'},
        ),
        migrations.AlterField(
            model_name='historicalhba1cresult',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
