# Generated by Django 3.0.9 on 2020-08-18 17:43

import edc_model.models.validators.date
import edc_protocol.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_prn", "0002_auto_20200818_2017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalintegratedcareclinicregistration",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Optional",
                null=True,
                verbose_name="Please give a brief summary of the opportunities and challenges in getting this clinic open.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalintegratedcareclinicregistration",
            name="date_opened",
            field=models.DateField(
                validators=[
                    edc_model.models.validators.date.date_not_future,
                    edc_protocol.validators.date_not_before_study_start,
                ],
                verbose_name="Date integrated clinic opened",
            ),
        ),
        migrations.AlterField(
            model_name="integratedcareclinicregistration",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Optional",
                null=True,
                verbose_name="Please give a brief summary of the opportunities and challenges in getting this clinic open.",
            ),
        ),
        migrations.AlterField(
            model_name="integratedcareclinicregistration",
            name="date_opened",
            field=models.DateField(
                validators=[
                    edc_model.models.validators.date.date_not_future,
                    edc_protocol.validators.date_not_before_study_start,
                ],
                verbose_name="Date integrated clinic opened",
            ),
        ),
    ]
