# Generated by Django 3.0.9 on 2020-10-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_prn", "0004_auto_20201021_0132"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofstudy",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comments"),
        ),
        migrations.AddField(
            model_name="historicalendofstudy",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comments"),
        ),
    ]
