# Generated by Django 3.0.9 on 2020-10-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inte_prn", "0007_auto_20201021_2218"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicallosstofollowuphiv",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Loss to Follow Up (HIV)",
            },
        ),
        migrations.AlterModelOptions(
            name="historicallosstofollowupncd",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Loss to Follow Up (NCD)",
            },
        ),
        migrations.AlterModelOptions(
            name="losstofollowuphiv",
            options={
                "verbose_name": "Loss to Follow Up (HIV)",
                "verbose_name_plural": "Loss to Follow Ups (HIV)",
            },
        ),
        migrations.AlterModelOptions(
            name="losstofollowupncd",
            options={
                "verbose_name": "Loss to Follow Up (NCD)",
                "verbose_name_plural": "Loss to Follow Ups (NCD)",
            },
        ),
    ]
