# Generated by Django 3.0.9 on 2021-01-23 17:42

import edc_model.models.validators.date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_prn", "0011_auto_20210122_2323"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsubjecttransferhiv",
            name="action_item",
        ),
        migrations.RemoveField(
            model_name="historicalsubjecttransferhiv",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalsubjecttransferhiv",
            name="parent_action_item",
        ),
        migrations.RemoveField(
            model_name="historicalsubjecttransferhiv",
            name="related_action_item",
        ),
        migrations.RemoveField(
            model_name="historicalsubjecttransferhiv",
            name="site",
        ),
        migrations.RemoveField(
            model_name="historicalsubjecttransferncd",
            name="action_item",
        ),
        migrations.RemoveField(
            model_name="historicalsubjecttransferncd",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalsubjecttransferncd",
            name="parent_action_item",
        ),
        migrations.RemoveField(
            model_name="historicalsubjecttransferncd",
            name="related_action_item",
        ),
        migrations.RemoveField(
            model_name="historicalsubjecttransferncd",
            name="site",
        ),
        migrations.DeleteModel(
            name="SubjectTransferHiv",
        ),
        migrations.DeleteModel(
            name="SubjectTransferNcd",
        ),
        migrations.AddField(
            model_name="endofstudy",
            name="transfer_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.models.validators.date.date_not_future],
                verbose_name="Date transferred, if applicable",
            ),
        ),
        migrations.AddField(
            model_name="historicalendofstudy",
            name="transfer_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.models.validators.date.date_not_future],
                verbose_name="Date transferred, if applicable",
            ),
        ),
        migrations.AddField(
            model_name="historicaloffschedulehiv",
            name="transfer_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.models.validators.date.date_not_future],
                verbose_name="Date transferred, if applicable",
            ),
        ),
        migrations.AddField(
            model_name="historicaloffschedulencd",
            name="transfer_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.models.validators.date.date_not_future],
                verbose_name="Date transferred, if applicable",
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalSubjectTransferHiv",
        ),
        migrations.DeleteModel(
            name="HistoricalSubjectTransferNcd",
        ),
    ]
