# Generated by Django 3.0.9 on 2020-11-24 18:01

import edc_model.models.validators.date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inte_ae", "0003_auto_20201124_1943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deathreport",
            name="death_date",
            field=models.DateField(
                validators=[edc_model.models.validators.date.date_not_future],
                verbose_name="Date of Death",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldeathreport",
            name="death_date",
            field=models.DateField(
                validators=[edc_model.models.validators.date.date_not_future],
                verbose_name="Date of Death",
            ),
        ),
    ]
