# Generated by Django 3.0.9 on 2021-01-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inte_ae", "0004_auto_20201124_2101"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deathreport",
            options={
                "verbose_name": "Death Report",
                "verbose_name_plural": "Death Reports",
            },
        ),
    ]
